[FIXED HUDSON-8113] prevent NoSuchMethodError when running with newer Hudson versions (> 1.327 - not sure at which version it breaks exactly)
git-svn-id: https://hudson.dev.java.net/svn/hudson/trunk/hudson/plugins@37019 71c3de6d-444a-0410-be80-ed276b4c234a